interface SharkdError {
    err: number;
}

interface SharkdRow {
    /** Values for each column. */
    c: string[];
    /** Frame number. */
    num: number;
    /** Background Color in hex */
    bg: string;
    /** Foreground Color in hex */
    fg: string;
}

interface SharkdFrame extends SharkdError {
    /** Background Color in hex */
    bg: string;
    /** Foreground Color in hex */
    fg: string;
    /** Array of follow filters:
     *      [0] Protocol,
     *      [1] Filter String
     */
    fol: [string, string][];
    /** Array of frame nodes with attributes */
    tree: SharkdTreeNode[];
}

interface SharkdTreeNode {
    /** Label */
    l: string;
    /** Filter String */
    f: string;
    /** If field is generated by Wireshark */
    g?: boolean;
    /** Subtree ett index */
    e?: number;
    /** Array of Subree Nodes */
    n?: SharkdTreeNode[];
}
