interface SharkdLoadFileRequest {
    req: "load"
    file: string
}

interface SharkdGetFramesRequest {
    req: "frames"
    skip: number
    limit: number
    // columnX: number | string
}

interface SharkdGetFrameTreeRequest {
    req: "frame"
    frame: number
    proto: 1
    bytes: 1
}

interface SharkdFrame {
    /** Values for each column. */
    c: string[]
    /** Frame number. */
    num: number
    /** Background Color in hex. */
    bg: string
    /** Foreground Color in hex. */
    fg: string
}

type SharkdByteRange = [number, number]

interface SharkdFrameResponse {
    err: number
    tree: SharkdFrameTreeNode[]
    bytes: string,
    byteRanges: SharkdByteRange[]
}

interface SharkdFrameTreeNode {
    /** Label */
    l: string
    /** Filter String */
    f: string
    /** If field is generated by Wireshark */
    g?: boolean
    /** Subtree ett index */
    e?: number
    /** Array of Subree Nodes */
    n?: SharkdFrameTreeNode[]
    /** Item start, Item length */
    h?: SharkdByteRange
    /** Severity */
    s?: "Chat" | "Note" | "Warning" | "Error"
}
